packages:
  - "packages/*"

minimumReleaseAgeExclude:
  - "astro"
  - "@astrojs/check"
  - "@astrojs/internal-helpers"
  - "@astrojs/markdown-remark"
  - "@astrojs/mdx"
  - "@astrojs/node"
  - "@astrojs/react"
  - "@astrojs/telemetry"
