{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "OrderCreated"
  },
  "paths": {},
  "components": {
    "schemas": {
      "AWSEvent": {
        "type": "object",
        "required": ["detail-type", "resources", "detail", "id", "source", "time", "region", "version", "account"],
        "x-amazon-events-detail-type": "OrderCreated",
        "x-amazon-events-source": "myapp.orders",
        "properties": {
          "detail": {
            "$ref": "#/components/schemas/OrderCreated"
          },
          "account": {
            "type": "string"
          },
          "detail-type": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "region": {
            "type": "string"
          },
          "resources": {
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "source": {
            "type": "string"
          },
          "time": {
            "type": "string",
            "format": "date-time"
          },
          "version": {
            "type": "string"
          }
        }
      },
      "OrderCreated": {
        "type": "object",
        "required": ["metadata", "data"],
        "properties": {
          "data": {
            "$ref": "#/components/schemas/Data"
          },
          "metadata": {
            "$ref": "#/components/schemas/Metadata"
          }
        }
      },
      "Data": {
        "type": "object",
        "required": ["user"],
        "properties": {
          "user": {
            "$ref": "#/components/schemas/User"
          }
        }
      },
      "Metadata": {
        "type": "object",
        "required": ["domain"],
        "properties": {
          "domain": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "required": ["id"],
        "properties": {
          "id": {
            "type": "string"
          }
        }
      }
    }
  }
}