export interface SidebarItem {
  label: string;
  slug?: string;
  items?: SidebarItem[];
  badge?: {
    text: string;
    color: string;
  };
  collapsed?: boolean;
}

export interface SidebarSection {
  label: string;
  items?: SidebarItem[];
  slug?: string;
  autogenerated?: {
    directory: string;
  };
  badge?: {
    text: string;
    color: string;
  };
  collapsed?: boolean;
}

export interface CustomDocsNavProps {
  sidebarItems: SidebarSection[];
  currentPath: string;
} 