openapi: 3.0.0
info:
  title: Test OpenAPI
  version: 1.0.0
paths:
  /test:
    get:
      summary: Test endpoint
      description: Test endpoint
      operationId: test
      responses:
        '200':
          description: Success