import { buildUrl } from '@utils/url-builder';

/** Maps fence languages and file extensions to an icon in `public/icons/languages`. */
const LANGUAGE_ICONS: Record<string, string> = {
  js: 'javascript',
  javascript: 'javascript',
  jsx: 'react',
  mjs: 'javascript',
  cjs: 'javascript',
  ts: 'typescript',
  typescript: 'typescript',
  tsx: 'react',
  node: 'nodejs',
  nodejs: 'nodejs',
  py: 'python',
  python: 'python',
  rb: 'ruby',
  ruby: 'ruby',
  php: 'php',
  cs: 'csharp',
  csharp: 'csharp',
  'c#': 'csharp',
  dotnet: 'dotnet',
  fsharp: 'fsharp',
  vb: 'dotnet',
  go: 'go',
  golang: 'go',
  java: 'java',
  kt: 'kotlin',
  kotlin: 'kotlin',
  gradle: 'gradle',
  swift: 'swift',
  rs: 'rust',
  rust: 'rust',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  'c++': 'cpp',
  dart: 'dart',
  scala: 'scala',
  r: 'r',
  perl: 'perl',
  pl: 'perl',
  lua: 'lua',
  hs: 'haskell',
  haskell: 'haskell',
  clj: 'clojure',
  clojure: 'clojure',
  erl: 'erlang',
  erlang: 'erlang',
  ml: 'ocaml',
  ocaml: 'ocaml',
  zig: 'zig',
  deno: 'deno',
  bun: 'bun',
  sol: 'solidity',
  solidity: 'solidity',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  shell: 'bash',
  console: 'bash',
  curl: 'curl',
  yaml: 'yaml',
  yml: 'yaml',
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  jsonschema: 'json-schema',
  'json-schema': 'json-schema',
  toml: 'toml',
  md: 'markdown',
  mdx: 'markdown',
  markdown: 'markdown',
  html: 'html',
  htm: 'html',
  vue: 'vue',
  svelte: 'svelte',
  angular: 'angular',
  css: 'css',
  scss: 'sass',
  less: 'css',
  graphql: 'graphql',
  gql: 'graphql',
  sql: 'mysql',
  mysql: 'mysql',
  postgres: 'postgresql',
  postgresql: 'postgresql',
  psql: 'postgresql',
  docker: 'docker',
  dockerfile: 'docker',
  git: 'git',
  diff: 'git',
  hcl: 'terraform',
  tf: 'terraform',
  terraform: 'terraform',
  nginx: 'nginx',
  kafka: 'kafka',
  '.net': 'dotnet',
  aspnet: 'dotnet',
  'asp.net': 'dotnet',
  vbnet: 'dotnet',
  'vb.net': 'dotnet',
  fs: 'fsharp',
  'f#': 'fsharp',
  kts: 'kotlin',
  groovy: 'gradle',
  maven: 'maven',
  pom: 'maven',
  spring: 'spring',
  jl: 'julia',
  julia: 'julia',
  f90: 'fortran',
  fortran: 'fortran',
  cr: 'crystal',
  crystal: 'crystal',
  nim: 'nim',
  elm: 'elm',
  purs: 'purescript',
  purescript: 'purescript',
  re: 'reasonml',
  reason: 'reasonml',
  reasonml: 'reasonml',
  flutter: 'flutter',
  grpc: 'grpc',
  sqlite: 'sqlite',
  mongodb: 'mongodb',
  mongo: 'mongodb',
  redis: 'redis',
  prisma: 'prisma',
  wasm: 'webassembly',
  wat: 'webassembly',
  webassembly: 'webassembly',
  sass: 'sass',
  tailwind: 'tailwind',
  tailwindcss: 'tailwind',
  http: 'httpie',
  httpie: 'httpie',
  swagger: 'swagger',
  ipynb: 'jupyter',
  jupyter: 'jupyter',
  android: 'android',
  ios: 'apple',
  objc: 'apple',
  objectivec: 'apple',
  'objective-c': 'apple',
  ino: 'arduino',
  arduino: 'arduino',
  unity: 'unity',
  vim: 'vim',
  hasura: 'hasura',
};

/** Languages that have a display name but no icon. */
const NAME_ONLY_LANGUAGES: Record<string, string> = {
  xml: 'XML',
  xsd: 'XML Schema',
  txt: 'Text',
  text: 'Text',
  plaintext: 'Text',
  plain: 'Text',
  ini: 'INI',
  properties: 'Properties',
  env: 'Env',
  dotenv: 'Env',
  makefile: 'Makefile',
  make: 'Makefile',
  cmake: 'CMake',
  tex: 'LaTeX',
  latex: 'LaTeX',
  csv: 'CSV',
  groovy: 'Groovy',
  elixir: 'Elixir',
  ex: 'Elixir',
  exs: 'Elixir',
  matlab: 'MATLAB',
  ps1: 'PowerShell',
  powershell: 'PowerShell',
  pwsh: 'PowerShell',
  bat: 'Batch',
  cmd: 'Batch',
  regex: 'Regex',
  mermaid: 'Mermaid',
  hbs: 'Handlebars',
  handlebars: 'Handlebars',
  ejs: 'EJS',
  pug: 'Pug',
  nix: 'Nix',
  cobol: 'COBOL',
  scheme: 'Scheme',
  racket: 'Racket',
  lisp: 'Lisp',
  ada: 'Ada',
  pascal: 'Pascal',
  prolog: 'Prolog',
  smalltalk: 'Smalltalk',
  vhdl: 'VHDL',
  verilog: 'Verilog',
  asm: 'Assembly',
  assembly: 'Assembly',
};

/** Formats that already have an icon elsewhere under `public/icons`. */
const SCHEMA_ICONS: Record<string, string> = {
  avro: 'avro',
  avsc: 'avro',
  proto: 'proto',
  protobuf: 'proto',
  openapi: 'openapi',
  asyncapi: 'asyncapi',
};

const LANGUAGE_NAMES: Record<string, string> = {
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  react: 'React',
  nodejs: 'Node.js',
  python: 'Python',
  ruby: 'Ruby',
  php: 'PHP',
  csharp: 'C#',
  dotnet: '.NET',
  go: 'Go',
  java: 'Java',
  kotlin: 'Kotlin',
  gradle: 'Gradle',
  swift: 'Swift',
  rust: 'Rust',
  c: 'C',
  cpp: 'C++',
  dart: 'Dart',
  scala: 'Scala',
  r: 'R',
  perl: 'Perl',
  lua: 'Lua',
  haskell: 'Haskell',
  clojure: 'Clojure',
  erlang: 'Erlang',
  ocaml: 'OCaml',
  zig: 'Zig',
  deno: 'Deno',
  bun: 'Bun',
  solidity: 'Solidity',
  bash: 'Shell',
  curl: 'cURL',
  yaml: 'YAML',
  json: 'JSON',
  'json-schema': 'JSON Schema',
  toml: 'TOML',
  markdown: 'Markdown',
  html: 'HTML',
  vue: 'Vue',
  svelte: 'Svelte',
  angular: 'Angular',
  css: 'CSS',
  graphql: 'GraphQL',
  mysql: 'SQL',
  postgresql: 'PostgreSQL',
  docker: 'Docker',
  git: 'Git',
  terraform: 'Terraform',
  nginx: 'NGINX',
  kafka: 'Kafka',
  avro: 'Avro',
  proto: 'Protobuf',
  openapi: 'OpenAPI',
  asyncapi: 'AsyncAPI',
  fsharp: 'F#',
  maven: 'Maven',
  spring: 'Spring',
  julia: 'Julia',
  fortran: 'Fortran',
  crystal: 'Crystal',
  nim: 'Nim',
  elm: 'Elm',
  purescript: 'PureScript',
  reasonml: 'ReasonML',
  flutter: 'Flutter',
  grpc: 'gRPC',
  sqlite: 'SQLite',
  mongodb: 'MongoDB',
  redis: 'Redis',
  prisma: 'Prisma',
  webassembly: 'WebAssembly',
  sass: 'Sass',
  tailwind: 'Tailwind CSS',
  httpie: 'HTTP',
  swagger: 'Swagger',
  jupyter: 'Jupyter',
  android: 'Android',
  apple: 'Apple',
  arduino: 'Arduino',
  unity: 'Unity',
  vim: 'Vim',
  hasura: 'Hasura',
};

const normalize = (value: string) => value.trim().toLowerCase();

const getExtension = (label?: string) => {
  const match = label?.trim().match(/\.([a-z0-9+#]+)$/i);
  return match?.[1];
};

const resolveIconKey = (language?: string, label?: string) => {
  for (const candidate of [language, getExtension(label)]) {
    if (!candidate) continue;
    const key = normalize(candidate);
    if (LANGUAGE_ICONS[key]) return LANGUAGE_ICONS[key];
    if (SCHEMA_ICONS[key]) return SCHEMA_ICONS[key];
  }
  return undefined;
};

/**
 * Human readable language name for a code panel, for example `Python` for `py`.
 * Falls back to the fence language as written, or the label when there is no language.
 */
export function getCodeLanguageName(language?: string, label?: string): string {
  const key = resolveIconKey(language, label);
  if (key && LANGUAGE_NAMES[key]) return LANGUAGE_NAMES[key];
  for (const candidate of [language, getExtension(label)]) {
    if (candidate && NAME_ONLY_LANGUAGES[normalize(candidate)]) return NAME_ONLY_LANGUAGES[normalize(candidate)];
  }
  const raw = language?.trim();
  if (raw) return raw.charAt(0).toUpperCase() + raw.slice(1);
  return label ?? '';
}

/**
 * Resolves an icon URL for a code panel from its fence language, falling back to the file
 * extension in the panel label. Returns `undefined` when there is no matching icon.
 */
export function getCodeLanguageIconUrl(language?: string, label?: string): string | undefined {
  for (const candidate of [language, getExtension(label)]) {
    if (!candidate) continue;
    const key = normalize(candidate);
    if (LANGUAGE_ICONS[key]) return buildUrl(`/icons/languages/${LANGUAGE_ICONS[key]}.svg`, true);
    if (SCHEMA_ICONS[key]) return buildUrl(`/icons/${SCHEMA_ICONS[key]}.svg`, true);
  }
  return undefined;
}
