asyncapi: 3.0.0

info:
  title: app-service-<APP>
  version: 1.0.0
  description: A service to do my awesome staff
  tags:
    - name: tag:<APP>
 
defaultContentType: application/json

channels:
  appChannel<APP>:
    address: app-channel-<APP>
    title: app events channel
    summary: A topic that distributes app events 
    messages:
      SomthingCreated<APP>:
        title: Somthing Created Event
        payload:
          type: object
          $ref: "#/components/schemas/SomthingCreatedEvent<APP>"
      SomthingTerminated<APP>:
        title: Somthing terminated Event
        payload:
          type: object
          $ref: "#/components/schemas/SomthingTerminatedEvent<APP>"

operations:
  onSomthingCreated<APP>:
    action: send
    summary: a new Somthing created
    channel:
      $ref: '#/channels/appChannel<APP>'
  onSomthingTerminated<APP>:
    action: send
    summary: a Somthing terminated
    channel:
      $ref: '#/channels/appChannel<APP>'

components:
  schemas:
    AotherCreatedEvent<APP>:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/cloudevents/spec/v1.0.1/spec.json'
        - type: object
          title: AotherCreatedEvent<APP>
          required:
            - type
            - data
          properties:
            type:
              type: string
              enum:
                - domain-a.aother.created.v1
            data:
              allOf:
                - $ref: "#/components/schemas/SomthingPayload<APP>"
                - type: object
                  required:
                   - creationDate
                  title: AotherCreatedEventDetails<APP>
                  properties:
                    creationDate:
                        type: string
                        format: DateTime

    SomthingCreatedEvent<APP>:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/cloudevents/spec/v1.0.1/spec.json'
        - type: object
          title: SomthingCreatedEvent<APP>
          required:
            - type
            - data
          properties:
            type:
              type: string
              enum:
                - domain-a.app.created.v1
            data:
              allOf:
                - $ref: "#/components/schemas/SomthingPayload<APP>"
                - type: object
                  required:
                   - creationDate
                  title: SomthingCreatedEventDetails<APP>
                  properties:
                    creationDate:
                        type: string
                        format: DateTime
    SomthingTerminatedEvent<APP>:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/cloudevents/spec/v1.0.1/spec.json'
        - type: object
          title: SomthingTerminatedEvent<APP>
          required:
            - type
            - data
          properties:
            type:
              type: string
              enum:
                - domain-a.app.terminated.v1
            data:
              allOf:
                - $ref: "#/components/schemas/SomthingPayload<APP>"
                - type: object
                  required:
                   - teminationDate
                  title: SomthingTerminatedEventDetails<APP>
                  properties:
                    teminationDate:
                        type: string
                        format: DateTime
    SomthingPayload<APP>:
      type: object
      title: SomthingPayload<APP>
      required:
        - SomthingId
        - Somthingtitle
        - SomthingOwner
      properties:
        somthingId:
          type: string
          format: uuid
        somthingtitle:
          type: string
          maxLength: 150
        somthingOwner:
          type: string
          maxLength: 64
        