/** @type {import('../../bin/eventcatalog.config').Config} */
export default {
  cId: '8027010c-f3d6-417a-8234-e2f46087fc56',
  title: 'FlowMart',
  tagline: 'Welcome to FlowMart EventCatalog. Here you can find all the information you need to know about our events and services (demo catalog).',
  organizationName: 'FlowMart',
  homepageLink: 'https://eventcatalog.dev',
  editUrl: 'https://github.com/event-catalog/eventcatalog/edit/main',
  port: 3000,
  outDir: 'dist',
  logo: {
    alt: 'FlowMart',
    src: '/logo.svg',
    text: 'FlowMart',
  },
  base: '/',
  trailingSlash: false,
  mermaid: {
    iconPacks: ['logos'],
  },
  rss: {
    enabled: true,
    limit: 15,
  },
  llmsTxt: {
    enabled: true,
  },
  chat: {
    enabled: true,
    similarityResults: 50,
    max_tokens: 4096,
    // 'Llama-3.2-3B-Instruct-q4f16_1-MLC is also good
    model: 'Hermes-3-Llama-3.2-3B-q4f16_1-MLC'
  },
  generators: [
    [
      "@eventcatalog/generator-ai", {
        debug: true,
        splitMarkdownFiles: false,
      }
    ],
  ],
  customDocs: {
    sidebar: [
      {
        label: 'Guides',
        badge: {
          text: 'New', color: 'green'
        },
        collapsed: false,
        items: [
          {
            label: 'Creating new microservices', autogenerated: { directory: 'guides/creating-new-microservices' }
          }
        ]
      },
      {
        label: 'Technical Architecture & Design',
        badge: {
          text: 'New', color: 'green'
        },
        collapsed: true,
        items: [
          {
            label: 'Architecture Decision Records', items: [
              { label: 'What is an Architecture Decision Record?', slug: 'technical-architecture-design/architecture-decision-records/01-architecture-desicion-record' },
              { label: 'Published', autogenerated: { directory: 'technical-architecture-design/architecture-decision-records/published', collapsed: true } },
              { label: 'Drafts', autogenerated: { directory: 'technical-architecture-design/architecture-decision-records/drafts', collapsed: true } },
              { label: 'Examples', autogenerated: { directory: 'technical-architecture-design/architecture-decision-records/examples', collapsed: true } },
            ]
          },
          { label: 'System Architecture Diagrams', autogenerated: { directory: 'technical-architecture-design/system-architecture-diagrams', collapsed: true } },
          { label: 'Infrastructure as Code', autogenerated: { directory: 'technical-architecture-design/infrastructure-as-code', collapsed: true } },
        ]
      },
      {
        label: 'Operations & Support',
        badge: {
          text: 'New', color: 'green'
        },
        collapsed: true,
        items: [
          { label: 'Runbooks', autogenerated: { directory: 'operations-and-support/runbooks', collapsed: true } },
        ]
      }
    ]
  }
};


/**
 * TODO: Collapsed groups (collapsed: true)
 */