/** @type {import('../../bin/eventcatalog.config').Config} */
export default {
  cId: '8027010c-f3d6-417a-8234-e2f46087fc56',
  title: 'FlowMart',
  tagline: 'Welcome to FlowMart EventCatalog. Here you can find all the information you need to know about our events and services (demo catalog).',
  organizationName: 'FlowMart',
  homepageLink: 'https://eventcatalog.dev',
  editUrl: 'https://github.com/event-catalog/eventcatalog/edit/main',
  port: 3000,
  logo: {
    alt: 'FlowMart',
    src: '/logo.svg',
    text: 'FlowMart',
  },
  base: '/',
  trailingSlash: false,
  mermaid: {
    iconPacks: ['logos'],
  },
  rss: {
    enabled: true,
    limit: 15,
  },
  llmsTxt: {
    enabled: true,
  },
  chat: {
    enabled: true,
    similarityResults: 50,
    max_tokens: 4096,
    // 'Llama-3.2-3B-Instruct-q4f16_1-MLC is also good
    model: 'Hermes-3-Llama-3.2-3B-q4f16_1-MLC'
  },
  generators: [
    [
      "@eventcatalog/generator-ai", {
        debug: true,
        splitMarkdownFiles: false,
      }
    ],
  ],
  customDocs: {
    sidebar: [
      {
        label: 'Guides',
        items: [
          {
            label: 'Creating new microservices', autogenerated: { directory: 'guides/creating-new-microservices' }
          },
          { label: 'Random Guide', slug: 'guides/02-random' },
        ]
      },
      {
        label: 'Architecture Records',
        items: [
          { label: 'What is an Architecture Decision Record?', slug: 'architecture-records/01-architecture-desicion-record' },

          {
            label: 'Published', autogenerated: { directory: 'architecture-records/published' }
          },
          {
            label: 'Drafts', autogenerated: { directory: 'architecture-records/drafts' }
          },
          {
            label: 'Examples', autogenerated: { directory: 'architecture-records/drafts' }
          },
          {
            label: 'Domain', items: [
              // Renders a resource as a nav item
              { label: 'MyDomain', resource: { id: 'MyDomain', collection: 'domains', version: 'latest' } },
              // Renders a resource as a nav item
              { label: 'MyDomain', architecture: { id: 'MyDomain', collection: 'domains', version: 'latest' } },
              // Renders a custom page
              { label: 'CustomPage', slug: 'random/custom-page' },
              // Renders all services as a nav item in a domain
              { label: 'MyDomain', services: { domain: 'MyDomain' } },
              {
                label: 'MyDomain', services: { domain: 'MyDomain' }
              },
            ]
          }
        ]
        // items: [
        //   { label: 'What is an Architecture Decision Record?', slug: 'architecture-records/01-architecture-desicion-record' },
        //   { label: 'Event-driven architecture adoption', slug: 'architecture-records/examples/02-eda-adoption' },
        //   { label: 'Broker of choice', slug: 'architecture-records/examples/03-broker-of-choice' },
        // ]
      }
    ]
  }
};
