export type SideBarConfig = {
  id: string;
  visible: boolean;
};

type ResourceDependency = {
  id: string;
  version?: string;
};

type CustomSideBarItem = {
  label: string;
  slug: string;
  items?: CustomSideBarItem[];
}

type ManualSideBarConfig = {
  label: string;
  badge?: {
    text: string;
    color: string;
  };
  collapsed?: boolean;
  items: CustomSideBarItem[];
};

type AutoGeneratedSideBarConfig = {
  label: string;
  autogenerated: {
    directory: string;
  };
  badge?: {
    text: string;
    color: string;
  };
  collapsed?: boolean;
};

export interface Config {
  title: string;
  tagline: false;
  organizationName: string;
  homepageLink: string;
  editUrl: string;
  landingPage?: string;
  base?: string;
  port?: string;
  trailingSlash?: boolean;
  rss?: {
    enabled: boolean;
    limit: number;
  };
  llmsTxt?: {
    enabled: boolean;
  };
  logo?: {
    alt: string;
    src: string;
    text?: string;
  };
  asyncAPI?: {
    renderParsedSchemas?: boolean;
  };
  mdxOptimize?: boolean;
  sidebar?: SideBarConfig[];
  docs: {
    sidebar: {
      type?: 'TREE_VIEW' | 'LIST_VIEW';
    };
  };
  dependencies?: {
    commands?: ResourceDependency[];
    events?: ResourceDependency[];
    services?: ResourceDependency[];
    domains?: ResourceDependency[];
  };
  mermaid?: {
    iconPacks?: string[];
  };
  chat?: {
    enabled: boolean;
    model?: string;
    max_tokens?: number;
    similarityResults?: number;
  };
  customDocs?: {
    sidebar?: (ManualSideBarConfig | AutoGeneratedSideBarConfig)[];
  }
}

// sidebar: [
//   {
//     label: 'Guides',
//     items: [
//       // Each item here is one entry in the navigation menu.
//       { label: 'Example Guide', slug: 'guides/example' },
//       { label: 'Random Guide', slug: 'guides/random' },
//     ],
//   },
//   {
//     label: 'Reference',
//     autogenerate: { directory: 'reference' },
//   },
// ],