/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
/// <reference types="likec4/vite-plugin-modules" />

declare const __EC_TRAILING_SLASH__: boolean;

// Virtual module generated by likec4-project-registry plugin
declare module 'virtual:likec4-projects' {
  export const projectRegistry: Record<string, () => Promise<{ LikeC4View: React.ComponentType<any> }>>;
  export const discoveredProjects: string[];
  export function getProjectLoader(projectName: string): () => Promise<{ LikeC4View: React.ComponentType<any> }>;
}

interface EventCatalogConfig {
  mermaid?: {
    iconPacks?: string[];
    enableSupportForElkLayout?: boolean;
  };
}

interface Window {
  eventcatalog?: EventCatalogConfig;
}
